In [1]:
import pandas as pd

In [2]:
df_azuelas = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/azuelas.csv")
df_azuelas

,adzeID,Context_artefacts::Site,Category,Context_artefacts::Region,Context_artefacts::Period,Context_artefacts::Type of context,Type,Length of artefact,Width of artefact,Thickness of artefact,Lower width of butt,Width of butt,Thickness of butt,Lower thickness of butt,Thickness of blade,Lower width of blade,Width of blade,Lower thickness of blade,Weight
0,562,Abu Rawash,model blade,Memphite region,"Old Kingdom, Dynasty 5",secondary,D,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,563,Abu Rawash,model blade,Memphite region,"Old Kingdom, Dynasty 5",secondary,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,558,Abu Rawash,model blade,Memphite region,"Old Kingdom, Dynasty 5",primary,D,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,67,Abu Rawash,model blade,Memphite region,"Old Kingdom, Dynasty 6",secondary,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,103,Abu Rawash,model blade,Memphite region,"Old Kingdom, Dynasty 5 late or 6",secondary,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,833,Saqqara,full size artefact blade,Memphite region,First Intermediate Period / Middle Kingdom,temple,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,834,Saqqara,full size artefact blade,Memphite region,First Intermediate Period / Middle Kingdom,temple,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,556,unknown,full size artefact blade,unknown,"Old Kingdom, Dynasty 5",unknown,D,209.0,86.0,11.0,NaN,42.0,8.8,NaN,2.0,NaN,86.0,NaN,500.3
292,631,unknown,full size artefact blade,NaN,"Old Kingdom, Dynasty 5",unknown,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,632,unknown,full size artefact blade,NaN,"Old Kingdom, Dynasty 5",unknown,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_tipi_azuelas = pd.DataFrame([df_azuelas.nunique(), df_azuelas.nunique()/len(df_azuelas) * 100, df_azuelas.dtypes]).\
    T.rename(columns = {0: "Card", 1: "%_Card", 2: "Tipo"})

df_tipi_azuelas

                                   Card     %_Card     Tipo
adzeID                              294      100.0    int64
Context_artefacts::Site              17   5.782313   object
Category                              4   1.360544   object
Context_artefacts::Region            12   4.081633   object
Context_artefacts::Period             9   3.061224   object
Context_artefacts::Type of context    8   2.721088   object
Type                                  4   1.360544   object
Length of artefact                   73  24.829932  float64
Width of artefact                    48  16.326531  float64
Thickness of artefact                26   8.843537  float64
Lower width of butt                   0        0.0  float64
Width of butt                        44  14.965986  float64
Thickness of butt                    27   9.183673  float64
Lower thickness of butt               0        0.0  float64
Thickness of blade                   23   7.823129  float64
Lower width of blade                  1   0.340136  float64
Width of blade                       48  16.326531  float64
Lower thickness of blade              0        0.0  float64
Weight                               51  17.346939  float64

In [4]:
df_tipi_azuelas["Clasificada_como"] = "Categorica"
df_tipi_azuelas.loc[df_tipi_azuelas.Card == 2, "Clasificada_como"] = "Binaria"
df_tipi_azuelas.loc[df_tipi_azuelas["Card"] > 10, "Clasificada_como"] ="Numerica Discreta"
df_tipi_azuelas.loc[df_tipi_azuelas["%_Card"] > 30, "Clasificada_como"] = "Numerica Continua"
df_tipi_azuelas

                                   Card     %_Card     Tipo   Clasificada_como
adzeID                              294      100.0    int64  Numerica Continua
Context_artefacts::Site              17   5.782313   object  Numerica Discreta
Category                              4   1.360544   object         Categorica
Context_artefacts::Region            12   4.081633   object  Numerica Discreta
Context_artefacts::Period             9   3.061224   object         Categorica
Context_artefacts::Type of context    8   2.721088   object         Categorica
Type                                  4   1.360544   object         Categorica
Length of artefact                   73  24.829932  float64  Numerica Discreta
Width of artefact                    48  16.326531  float64  Numerica Discreta
Thickness of artefact                26   8.843537  float64  Numerica Discreta
Lower width of butt                   0        0.0  float64         Categorica
Width of butt                        44  14.965986  float64  Numerica Discreta
Thickness of butt                    27   9.183673  float64  Numerica Discreta
Lower thickness of butt               0        0.0  float64         Categorica
Thickness of blade                   23   7.823129  float64  Numerica Discreta
Lower width of blade                  1   0.340136  float64         Categorica
Width of blade                       48  16.326531  float64  Numerica Discreta
Lower thickness of blade              0        0.0  float64         Categorica
Weight                               51  17.346939  float64  Numerica Discreta

In [5]:
df_hachas = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/hachas.csv")
df_hachas

,axeID,Context_artefacts::Site,Context_artefacts::Region,Category,Context_artefacts::Period,Context_artefacts::Type of context,Type,Heigth of artefact,Maximal width,Maximal thickness,Width of blade,Thickness of blade,Weight
0,101,Abu Rawash,Memphite region,full size artefact blade,"Old Kingdom, Dynasty 4",primary probably,B,180.0,160.0,NaN,NaN,NaN,946.42
1,103,Abusir,Memphite region,model blade,"Old Kingdom, Dynasty 5",secondary,A,50.0,50.0,1.0,NaN,NaN,NaN
2,338,Abusir,Memphite region,model blade,"Old Kingdom, Dynasty 5",secondary probably,A,NaN,NaN,NaN,NaN,NaN,NaN
3,296,Abusir,Memphite region,model blade,"Old Kingdom, Dynasty 5",secondary,A,44.0,61.0,2.5,NaN,NaN,NaN
4,393,Abusir,Memphite region,model blade,"Old Kingdom, Dynasty 5",secondary,A,37.0,39.4,0.8,NaN,NaN,6.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,177,Saqqara,Memphite region,gilded model blade,"Old Kingdom, Dynasty 6",secondary,A,NaN,NaN,NaN,NaN,NaN,NaN
149,312,Saqqara,Memphite region,model blade,"Old Kingdom, Dynasty 6",secondary probably,A,NaN,NaN,NaN,NaN,NaN,NaN
150,301,Saqqara,Memphite region,model blade,"Old Kingdom, Dynasty 6",secondary,A,51.0,56.0,3.0,NaN,NaN,NaN
151,429,Saqqara,Memphite region,model artefact with handle,NaN,unknown,A,NaN,NaN,NaN,NaN,NaN,NaN
152,297,unknown,unknown,full size artefact blade,"Old Kingdom, Dynasty 6",unknown,B,119.0,129.0,NaN,NaN,NaN,NaN

In [6]:
df_tipi_hachas = pd.DataFrame([df_hachas.nunique(), df_hachas.nunique()/len(df_hachas) * 100, df_hachas.dtypes]).\
    T.rename(columns = {0: "Card", 1: "%_Card", 2: "Tipo"})

df_tipi_hachas

                                   Card     %_Card     Tipo
axeID                               153      100.0    int64
Context_artefacts::Site              17  11.111111   object
Context_artefacts::Region            11   7.189542   object
Category                              5   3.267974   object
Context_artefacts::Period             9   5.882353   object
Context_artefacts::Type of context    7   4.575163   object
Type                                  3   1.960784   object
Heigth of artefact                   35  22.875817  float64
Maximal width                        38  24.836601  float64
Maximal thickness                    12   7.843137  float64
Width of blade                       19  12.418301  float64
Thickness of blade                    4   2.614379  float64
Weight                               27  17.647059  float64

In [7]:
df_tipi_hachas["Clasificada_como"] = "Categorica"
df_tipi_hachas.loc[df_tipi_hachas.Card == 2, "Clasificada_como"] = "Binaria"
df_tipi_hachas.loc[df_tipi_hachas["Card"] > 10, "Clasificada_como"] ="Numerica Discreta"
df_tipi_hachas.loc[df_tipi_hachas["%_Card"] > 30, "Clasificada_como"] = "Numerica Continua"
df_tipi_hachas

                                   Card     %_Card     Tipo   Clasificada_como
axeID                               153      100.0    int64  Numerica Continua
Context_artefacts::Site              17  11.111111   object  Numerica Discreta
Context_artefacts::Region            11   7.189542   object  Numerica Discreta
Category                              5   3.267974   object         Categorica
Context_artefacts::Period             9   5.882353   object         Categorica
Context_artefacts::Type of context    7   4.575163   object         Categorica
Type                                  3   1.960784   object         Categorica
Heigth of artefact                   35  22.875817  float64  Numerica Discreta
Maximal width                        38  24.836601  float64  Numerica Discreta
Maximal thickness                    12   7.843137  float64  Numerica Discreta
Width of blade                       19  12.418301  float64  Numerica Discreta
Thickness of blade                    4   2.614379  float64         Categorica
Weight                               27  17.647059  float64  Numerica Discreta

In [8]:
df_cinceles = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/cinceles.csv")
df_cinceles

,chiselID,Context_artefacts::Site,Context_artefacts::Region,Category,Context_artefacts::Period,Context_artefacts::Type of context,Type,Length of chisel,Thickness of blade,Width of blade,Maximal width,Maximal thickness,Weight
0,174,Abu Rawash,Memphite region,model blade,"Old Kingdom, Dynasty 5",secondary,A,NaN,NaN,NaN,NaN,NaN,NaN
1,175,Abu Rawash,Memphite region,model blade,"Old Kingdom, Dynasty 5",secondary,D,NaN,NaN,NaN,NaN,NaN,NaN
2,957,Abu Rawash,Memphite region,model blade,"Old Kingdom, Dynasty 5",primary,D,48.0,NaN,NaN,NaN,NaN,NaN
3,958,Abu Rawash,Memphite region,model blade,"Old Kingdom, Dynasty 5",primary,A,64.0,NaN,NaN,NaN,NaN,NaN
4,959,Abu Rawash,Memphite region,model blade,"Old Kingdom, Dynasty 5",primary,A,50.5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,375,unknown,Nubia,full size artefact with handle,"Old Kingdom, Dynasty 4",unknown,C,240.0,NaN,NaN,NaN,NaN,955.0
616,377,unknown,unknown,full size artefact blade,"Old Kingdom, Dynasty 5",unknown,E,198.0,2.0,11.0,30.0,7.6,273.4
617,376,unknown,unknown,full size artefact blade,"Old Kingdom, Dynasty 5",unknown,E,238.0,NaN,11.0,35.0,7.9,398.1
618,378,unknown,NaN,full size artefact blade,"Old Kingdom, Dynasty 5",unknown,E,NaN,NaN,NaN,NaN,NaN,NaN
619,379,unknown,unknown,full size artefact blade,Old Kingdom general,unknown,G,240.0,NaN,NaN,NaN,NaN,758.0

In [9]:
df_tipi_cinceles = pd.DataFrame([df_cinceles.nunique(), df_cinceles.nunique()/len(df_cinceles) * 100, df_cinceles.dtypes]).\
    T.rename(columns = {0: "Card", 1: "%_Card", 2: "Tipo"})

df_tipi_cinceles

                                   Card     %_Card     Tipo
chiselID                            620      100.0    int64
Context_artefacts::Site              19   3.064516   object
Context_artefacts::Region            12   1.935484   object
Category                              5   0.806452   object
Context_artefacts::Period            10   1.612903   object
Context_artefacts::Type of context    8   1.290323   object
Type                                  9   1.451613   object
Length of chisel                    119  19.193548  float64
Thickness of blade                   23   3.709677  float64
Width of blade                       61    9.83871  float64
Maximal width                        80  12.903226  float64
Maximal thickness                    59   9.516129  float64
Weight                              103  16.612903  float64

In [10]:
df_tipi_cinceles["Clasificada_como"] = "Categorica"
df_tipi_cinceles.loc[df_tipi_cinceles.Card == 2, "Clasificada_como"] = "Binaria"
df_tipi_cinceles.loc[df_tipi_cinceles["Card"] > 10, "Clasificada_como"] ="Numerica Discreta"
df_tipi_cinceles.loc[df_tipi_cinceles["%_Card"] > 30, "Clasificada_como"] = "Numerica Continua"
df_tipi_cinceles

                                   Card     %_Card     Tipo   Clasificada_como
chiselID                            620      100.0    int64  Numerica Continua
Context_artefacts::Site              19   3.064516   object  Numerica Discreta
Context_artefacts::Region            12   1.935484   object  Numerica Discreta
Category                              5   0.806452   object         Categorica
Context_artefacts::Period            10   1.612903   object         Categorica
Context_artefacts::Type of context    8   1.290323   object         Categorica
Type                                  9   1.451613   object         Categorica
Length of chisel                    119  19.193548  float64  Numerica Discreta
Thickness of blade                   23   3.709677  float64  Numerica Discreta
Width of blade                       61    9.83871  float64  Numerica Discreta
Maximal width                        80  12.903226  float64  Numerica Discreta
Maximal thickness                    59   9.516129  float64  Numerica Discreta
Weight                              103  16.612903  float64  Numerica Discreta

In [11]:
df_espejos = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/espejos.csv")
df_espejos

,mirrorID,Context_artefacts::Site,Context_artefacts::Region,Category,Context_artefacts::Period,Context_artefacts::Type of context,Type,Heigth of artefact,Width of artefact,Thickness of artefact,Heigth of disc,Width of disc,Thickness of disc,Weight
0,60,Abydos,Abydos,model blade,"Old Kingdom, late / First Intermediate period",primary,C,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,208,Abydos,Abydos,full size artefact blade,"Old Kingdom, late / First Intermediate period",settlement,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,304,Abydos,Abydos,full size artefact blade,"Old Kingdom, Dynasty 5",secondary,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,52,Adindan,Nubia,full size artefact blade,Old Kingdom general,primary,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,273,Aniba,Nubia,full size artefact blade,"Old Kingdom, Dynasty 6",primary,C,240.0,220.0,NaN,NaN,220.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,300,unknown,unknown,full size artefact blade,"Old Kingdom, Dynasty 6",unknown,C,164.0,150.0,4.5,139.0,150.0,4.5,NaN
122,301,unknown,unknown,full size artefact blade,"Old Kingdom, Dynasty 6",unknown,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,303,unknown,unknown,full size artefact blade,"Old Kingdom, Dynasty 6",unknown,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,260,Zawiyet el-Mayitin,between Fayum and Beni Hasan,full size artefact blade,"Old Kingdom, Dynasty 6",unknown,C,181.0,210.0,6.0,118.0,210.0,4.4,328.6
125,259,Zawiyet el-Mayitin,between Fayum and Beni Hasan,full size artefact blade,"Old Kingdom, Dynasty 6",unknown,D,176.0,167.0,3.5,147.0,167.0,NaN,326.9

In [12]:
df_tipi_espejos = pd.DataFrame([df_espejos.nunique(), df_espejos.nunique()/len(df_espejos) * 100, df_espejos.dtypes]).\
    T.rename(columns = {0: "Card", 1: "%_Card", 2: "Tipo"})

df_tipi_espejos

                                   Card     %_Card     Tipo
mirrorID                            126      100.0    int64
Context_artefacts::Site              26  20.634921   object
Context_artefacts::Region            13   10.31746   object
Category                              3   2.380952   object
Context_artefacts::Period             8   6.349206   object
Context_artefacts::Type of context    7   5.555556   object
Type                                  6   4.761905   object
Heigth of artefact                   42  33.333333  float64
Width of artefact                    43  34.126984  float64
Thickness of artefact                13   10.31746  float64
Heigth of disc                       37  29.365079  float64
Width of disc                        41  32.539683  float64
Thickness of disc                    10   7.936508  float64
Weight                               27  21.428571  float64

In [13]:
df_tipi_espejos["Clasificada_como"] = "Categorica"
df_tipi_espejos.loc[df_tipi_espejos.Card == 2, "Clasificada_como"] = "Binaria"
df_tipi_espejos.loc[df_tipi_espejos["Card"] > 10, "Clasificada_como"] ="Numerica Discreta"
df_tipi_espejos.loc[df_tipi_espejos["%_Card"] > 30, "Clasificada_como"] = "Numerica Continua"
df_tipi_espejos

                                   Card     %_Card     Tipo   Clasificada_como
mirrorID                            126      100.0    int64  Numerica Continua
Context_artefacts::Site              26  20.634921   object  Numerica Discreta
Context_artefacts::Region            13   10.31746   object  Numerica Discreta
Category                              3   2.380952   object         Categorica
Context_artefacts::Period             8   6.349206   object         Categorica
Context_artefacts::Type of context    7   5.555556   object         Categorica
Type                                  6   4.761905   object         Categorica
Heigth of artefact                   42  33.333333  float64  Numerica Continua
Width of artefact                    43  34.126984  float64  Numerica Continua
Thickness of artefact                13   10.31746  float64  Numerica Discreta
Heigth of disc                       37  29.365079  float64  Numerica Discreta
Width of disc                        41  32.539683  float64  Numerica Continua
Thickness of disc                    10   7.936508  float64         Categorica
Weight                               27  21.428571  float64  Numerica Discreta

In [14]:
df_sierras = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/sierras.csv")
df_sierras

,sawID,Context_artefacts::Site,Context_artefacts::Region,Context_artefacts::Period,Type,Context_artefacts::Type of context,Category,Length of artefact,Width of artefact,Maximal thickness,Length of blade,Width of blade,Thickness of blade,Weight
0,208,Abu Rawash,Memphite region,"Old Kingdom, Dynasty 5",B,primary,model blade,80.0,NaN,NaN,NaN,NaN,NaN,NaN
1,72,Abusir,Memphite region,"Old Kingdom, Dynasty 5",B,secondary,model blade,160.0,21.0,NaN,145.0,21.0,NaN,NaN
2,200,Abusir,Memphite region,"Old Kingdom, Dynasty 5",B,secondary probably,model blade,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17,Abusir,Memphite region,"Old Kingdom, Dynasty 5",B,secondary,model blade,115.0,16.0,NaN,95.0,16.0,1.0,NaN
4,235,Abusir,Memphite region,"Old Kingdom, Dynasty 5",B,secondary,model blade,116.0,15.0,2.2,99.0,15.0,1.0,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,76,Saqqara,Memphite region,"Old Kingdom, Dynasty 6",B,secondary,gilded model blade,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,149,Saqqara,Memphite region,"Old Kingdom, Dynasty 6",B,secondary probably,model blade,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,150,Saqqara,Memphite region,"Old Kingdom, Dynasty 6",A,secondary probably,model blade,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,244,Saqqara,Memphite region,First Intermediate Period / Middle Kingdom,undeterminable,temple,full size artefact blade,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,226,unknown,unknown,First Intermediate period,A,unknown,full size artefact blade,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_tipi_sierras = pd.DataFrame([df_sierras.nunique(), df_sierras.nunique()/len(df_sierras) * 100, df_sierras.dtypes]).\
    T.rename(columns = {0: "Card", 1: "%_Card", 2: "Tipo"})

df_tipi_sierras

                                   Card     %_Card     Tipo
sawID                               145      100.0    int64
Context_artefacts::Site              10   6.896552   object
Context_artefacts::Region             6   4.137931   object
Context_artefacts::Period             9   6.206897   object
Type                                  3   2.068966   object
Context_artefacts::Type of context    6   4.137931   object
Category                              4   2.758621   object
Length of artefact                   20  13.793103  float64
Width of artefact                    16  11.034483  float64
Maximal thickness                     9   6.206897  float64
Length of blade                      14   9.655172  float64
Width of blade                       16  11.034483  float64
Thickness of blade                    7   4.827586  float64
Weight                               10   6.896552  float64

In [16]:
df_tipi_sierras["Clasificada_como"] = "Categorica"
df_tipi_sierras.loc[df_tipi_sierras.Card == 2, "Clasificada_como"] = "Binaria"
df_tipi_sierras.loc[df_tipi_sierras["Card"] > 10, "Clasificada_como"] ="Numerica Discreta"
df_tipi_sierras.loc[df_tipi_sierras["%_Card"] > 30, "Clasificada_como"] = "Numerica Continua"
df_tipi_sierras

                                   Card     %_Card     Tipo   Clasificada_como
sawID                               145      100.0    int64  Numerica Continua
Context_artefacts::Site              10   6.896552   object         Categorica
Context_artefacts::Region             6   4.137931   object         Categorica
Context_artefacts::Period             9   6.206897   object         Categorica
Type                                  3   2.068966   object         Categorica
Context_artefacts::Type of context    6   4.137931   object         Categorica
Category                              4   2.758621   object         Categorica
Length of artefact                   20  13.793103  float64  Numerica Discreta
Width of artefact                    16  11.034483  float64  Numerica Discreta
Maximal thickness                     9   6.206897  float64         Categorica
Length of blade                      14   9.655172  float64  Numerica Discreta
Width of blade                       16  11.034483  float64  Numerica Discreta
Thickness of blade                    7   4.827586  float64         Categorica
Weight                               10   6.896552  float64         Categorica

In [17]:
df_agujas = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/agujas.csv")
df_agujas

,needleID,Context_artefacts::Site,Context_artefacts::Region,Category,Context_artefacts::Period,Context_artefacts::Type of context,Type,Length of artefact,Maximal width,Maximal thickness,Width of head,Thickness of head,Diameter of shaft,Weight
0,58,Abu Rawash,Memphite region,undeterminable,"Old Kingdom, Dynasty 4",secondary,undeterminable,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,59,Abu Rawash,Memphite region,undeterminable,"Old Kingdom, Dynasty 4",secondary probably,undeterminable,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,60,Abu Rawash,Memphite region,undeterminable,"Old Kingdom, Dynasty 4",settlement,undeterminable,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,84,Abusir,Memphite region,full size artefact blade,"Old Kingdom, Dynasty 5",secondary,B,73.0,4.0,2.0,4.0,NaN,NaN,NaN
4,61,Abusir,Memphite region,full size artefact blade,"Old Kingdom, Dynasty 5",secondary,B,73.0,4.0,3.0,4.0,NaN,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,116,Matmar,between Asiut and Abydos,undeterminable,"Old Kingdom, Dynasty 6",primary,undeterminable,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,55,Mostagedda,between Asiut and Abydos,full size artefact blade,"Old Kingdom, Dynasty 6",primary probably,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,66,Naga ed-Deir,between Asiut and Abydos,undeterminable,"Old Kingdom, late / First Intermediate period",secondary,undeterminable,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,73,Shem Nishai,Nubia,full size artefact blade,Old Kingdom general,primary probably,undeterminable,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,56,Sinki (Abydosâ€“South),Abydos,undeterminable,"Old Kingdom, Dynasty 6",primary probably,undeterminable,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_tipi_agujas = pd.DataFrame([df_agujas.nunique(), df_agujas.nunique()/len(df_agujas) * 100, df_agujas.dtypes]).\
    T.rename(columns = {0: "Card", 1: "%_Card", 2: "Tipo"})

df_tipi_agujas

                                   Card     %_Card     Tipo
needleID                            112      100.0    int64
Context_artefacts::Site              13  11.607143   object
Context_artefacts::Region             7       6.25   object
Category                              2   1.785714   object
Context_artefacts::Period             7       6.25   object
Context_artefacts::Type of context    6   5.357143   object
Type                                  4   3.571429   object
Length of artefact                   52  46.428571  float64
Maximal width                        25  22.321429  float64
Maximal thickness                    23  20.535714  float64
Width of head                        20  17.857143  float64
Thickness of head                    18  16.071429  float64
Diameter of shaft                    19  16.964286  float64
Weight                               24  21.428571  float64

In [19]:
df_tipi_agujas["Clasificada_como"] = "Categorica"
df_tipi_agujas.loc[df_tipi_agujas.Card == 2, "Clasificada_como"] = "Binaria"
df_tipi_agujas.loc[df_tipi_agujas["Card"] > 10, "Clasificada_como"] ="Numerica Discreta"
df_tipi_agujas.loc[df_tipi_agujas["%_Card"] > 30, "Clasificada_como"] = "Numerica Continua"
df_tipi_agujas

                                   Card     %_Card     Tipo   Clasificada_como
needleID                            112      100.0    int64  Numerica Continua
Context_artefacts::Site              13  11.607143   object  Numerica Discreta
Context_artefacts::Region             7       6.25   object         Categorica
Category                              2   1.785714   object            Binaria
Context_artefacts::Period             7       6.25   object         Categorica
Context_artefacts::Type of context    6   5.357143   object         Categorica
Type                                  4   3.571429   object         Categorica
Length of artefact                   52  46.428571  float64  Numerica Continua
Maximal width                        25  22.321429  float64  Numerica Discreta
Maximal thickness                    23  20.535714  float64  Numerica Discreta
Width of head                        20  17.857143  float64  Numerica Discreta
Thickness of head                    18  16.071429  float64  Numerica Discreta
Diameter of shaft                    19  16.964286  float64  Numerica Discreta
Weight                               24  21.428571  float64  Numerica Discreta