In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df_azuelas = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/azuelas.csv")
df_hachas = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/hachas.csv")
df_cinceles = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/cinceles.csv")
df_espejos = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/espejos.csv")
df_sierras = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/sierras.csv")
df_agujas = pd.read_csv("/Users/bastiensegalas/Desktop/EDA/data/procesado/agujas.csv")

In [3]:
def variabilidad(df):
    df_var = df.describe().loc[["std", "mean"]].T
    df_var["CV"] = df_var["std"]/df_var["mean"]
    return df_var

In [4]:
variabilidad(df_azuelas)

                                 std        mean        CV
adzeID                    232.200994  518.761905  0.447606
Length of artefact         30.528324   76.416783  0.399498
Width of artefact          13.506162   21.632800  0.624337
Thickness of artefact       5.677808    2.881034  1.970753
Lower width of butt              NaN         NaN       NaN
Width of butt               5.811183   13.270000  0.437919
Thickness of butt           1.652899    2.300000  0.718652
Lower thickness of butt          NaN         NaN       NaN
Thickness of blade          6.281518    2.137912  2.938155
Lower width of blade             NaN    1.000000       NaN
Width of blade             12.971269   21.013821  0.617273
Lower thickness of blade         NaN         NaN       NaN
Weight                     78.683882   29.914912  2.630256

In [5]:
variabilidad(df_hachas)

                           std        mean        CV
axeID               129.495267  266.673203  0.485595
Heigth of artefact   30.346694   44.123333  0.687770
Maximal width        28.627232   40.456923  0.707598
Maximal thickness     0.787905    1.465000  0.537819
Width of blade       11.382285   44.172727  0.257677
Thickness of blade    0.624238    1.255556  0.497181
Weight              448.815120  153.710667  2.919870

In [6]:
variabilidad(df_cinceles)

                           std        mean        CV
chiselID            322.584106  605.943548  0.532367
Length of chisel     33.148383   77.933731  0.425341
Thickness of blade    4.996841    3.561538  1.403001
Width of blade        7.512041    5.896565  1.273969
Maximal width        10.280725    8.647988  1.188800
Maximal thickness     6.221475    4.816000  1.291834
Weight               93.323218   24.680769  3.781212

In [7]:
variabilidad(df_espejos)

                              std        mean        CV
mirrorID                89.571647  176.007937  0.508907
Heigth of artefact      67.746145  154.565217  0.438301
Width of artefact       48.407751  146.557692  0.330298
Thickness of artefact    2.593813    4.455000  0.582225
Heigth of disc          49.960032  136.035714  0.367257
Width of disc           48.863258  146.880000  0.332675
Thickness of disc        1.988207    3.828571  0.519308
Weight                 379.568503  353.730370  1.073045

In [8]:
variabilidad(df_sierras)

                          std        mean        CV
sawID               90.684433  212.544828  0.426660
Length of artefact  36.650949  127.277778  0.287960
Width of artefact   10.835806   19.152941  0.565752
Maximal thickness    2.502832    2.375000  1.053824
Length of blade     35.043659  116.483871  0.300846
Width of blade      10.835806   19.152941  0.565752
Thickness of blade   0.158623    0.987097  0.160697
Weight               1.279560    3.450000  0.370887

In [9]:
variabilidad(df_agujas)

                          std        mean        CV
needleID            46.095418  105.776786  0.435780
Length of artefact  24.050810   52.704918  0.456330
Maximal width        6.623456    4.364912  1.517432
Maximal thickness    6.746691    4.696491  1.436539
Width of head        6.542106    4.492308  1.456291
Thickness of head    6.231288    4.511765  1.381120
Diameter of shaft    4.465828    2.984444  1.496368
Weight               0.986985    1.338000  0.737657